openapi: 3.0.0
info:
  title: temperature_sensor
  description: Offers access to the sensor's data.
  version: 1.0.0
servers:
  - url: http://127.0.0.1/8888
    description: HTTP sensor server
paths:
  /temperature/{unit}:
    get:
      summary: Returns the temperature info.
      description: Temperature info obtained from the sensor
      operationId: get-temperature
      parameters:
        - name: unit
          in: path
          required: true
          description: Unit in which the temperature value will be given.
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema: 
                type: object
                properties:
                  v: 
                    type: integer
                    format: int32
                  u:
                    type: string
                  t:
                    type: number
                    format: double
        '404':
          description: Not Found
        default:
          description: Unexpected error